import 'dart:async';
import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:just_audio_media_kit/just_audio_media_kit.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter/services.dart';
import 'package:flutter_inappwebview/flutter_inappwebview.dart';
import 'package:flutter_logs/flutter_logs.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:receive_intent/receive_intent.dart' as intents;
import 'package:stack_trace/stack_trace.dart';
import 'package:hibiki/src/utils/spacing.dart';
import 'package:wakelock_plus/wakelock_plus.dart';
import 'package:hibiki/models.dart';
import 'package:hibiki_dictionary/hibiki_dictionary.dart';
import 'package:hibiki/pages.dart';
import 'package:hibiki/popup_main.dart' as popup_entrypoint;
import 'package:hibiki/src/sync/dropbox_sync_backend.dart';
import 'package:hibiki/src/sync/onedrive_sync_backend.dart';
import 'package:hibiki/src/sync/sync_backend.dart';
import 'package:hibiki/src/sync/sync_error_messages.dart';
import 'package:hibiki/src/utils/misc/channel_constants.dart';
import 'package:hibiki/utils.dart';
import 'package:hibiki/src/shortcuts/global_navigation.dart';
import 'package:hibiki/src/shortcuts/shortcut_defaults.dart';
import 'package:hibiki/src/platform/platform_services.dart';
import 'package:hibiki/src/platform/platform_providers.dart';
import 'package:share_plus/share_plus.dart';

Color? _savedSplashColor;

@pragma('vm:entry-point')
void popupMain() {
  popup_entrypoint.popupMain();
}

/// Application execution starts here.
void main() {
  /// Run and handle an error zone to customise the action performed upon
  /// an error or exception. This allows for error logging for debug purposes
  /// as well as communicating errors to Crashlytics if enabled.
  runZonedGuarded<Future<void>>(() async {
    /// Necessary to initialise Flutter when running native code before
    /// starting the application.
    final binding = WidgetsFlutterBinding.ensureInitialized();
    JustAudioMediaKit.title = 'Hibiki';
    JustAudioMediaKit.ensureInitialized();

    /// Ensure no pop-in for the app icon.
    binding.addPostFrameCallback((_) async {
      final context = binding.rootElement;
      if (context != null) {
        precacheImage(const AssetImage('assets/meta/icon.png'), context);
      }
    });

    /// Ensure wake prevention is disabled if not reverted from entering a
    /// media source.  WakelockPlus supports all desktop and mobile platforms,
    /// so clear it unconditionally; the try-catch handles unsupported targets.
    try {
      WakelockPlus.disable();
    } catch (e) {
      debugPrint('[Hibiki] wakelock disable on startup failed: $e');
    }
    if (Platform.isAndroid || Platform.isIOS) {
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
    }

    // Match system bar overlays to the platform brightness immediately so the
    // status bar and navigation bar don't flash white on dark-mode devices.
    final platformBrightness =
        WidgetsBinding.instance.platformDispatcher.platformBrightness;
    SystemChrome.setSystemUIOverlayStyle(
      platformBrightness == Brightness.dark
          ? SystemUiOverlayStyle.light.copyWith(
              statusBarColor: Colors.transparent,
              systemNavigationBarColor: Colors.transparent,
              systemNavigationBarContrastEnforced: false,
            )
          : SystemUiOverlayStyle.dark.copyWith(
              statusBarColor: Colors.transparent,
              systemNavigationBarColor: Colors.transparent,
              systemNavigationBarContrastEnforced: false,
            ),
    );

    if (Platform.isAndroid || Platform.isIOS) {
      try {
        final raw =
            await HibikiChannels.splash.invokeMethod<int>('getSplashColor');
        if (raw != null && raw != 0) _savedSplashColor = Color(raw);
      } catch (e) {
        debugPrint('[Hibiki] getSplashColor failed: $e');
      }

      SystemChrome.setPreferredOrientations([
        DeviceOrientation.portraitUp,
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]);
    }

    /// Some packages propagate their [StackTrace] in an unusual format as
    /// opposed to the format generated by Dart. This function allows the
    /// Flutter framework to handle such formats so they can be displayed
    /// appropriately.
    FlutterError.demangleStackTrace = (stack) {
      if (stack is Trace) {
        return stack.vmTrace;
      }
      if (stack is Chain) {
        return stack.toTrace().vmTrace;
      }
      return stack;
    };

    /// Construct platform-specific service implementations once, before the
    /// provider container is created.  This value object is injected into both
    /// [platformServicesProvider] (for widget-layer access) and [AppModel]
    /// (via [appProvider]).
    final platformServices = PlatformServices.forCurrentPlatform();

    /// Create the provider container before running the app so the same
    /// [AppModel] instance is shared between the widget tree and the
    /// initialisation call below.
    final container = ProviderContainer(
      overrides: [
        platformServicesProvider.overrideWithValue(platformServices),
      ],
    );

    /// Start the application immediately so the user sees the loading page
    /// rather than a blank white screen while initialisation is in progress.
    runApp(
      UncontrolledProviderScope(
        container: container,
        child: const HoshiReaderApp(),
      ),
    );

    /// Initialise error log service.
    await ErrorLogService.instance.init();
    await DebugLogService.instance.init();

    /// Initialise local file-based logging (mobile only).
    if (Platform.isAndroid || Platform.isIOS) {
      await FlutterLogs.initLogs(
        logLevelsEnabled: [
          LogLevel.INFO,
          LogLevel.WARNING,
          LogLevel.ERROR,
          LogLevel.SEVERE
        ],
        timeStampFormat: TimeStampFormat.DATE_FORMAT_1,
        directoryStructure: DirectoryStructure.FOR_DATE,
        logTypesEnabled: ['device', 'network', 'errors'],
        logFileExtension: LogFileExtension.LOG,
        logsRetentionPeriodInDays: 7,
      );
    }

    /// Run the heavy initialisation after the first frame has been scheduled.
    /// [AppModel.isInitialised] will flip to true and notify listeners when
    /// done, causing [HoshiReaderApp] to navigate from [LoadingPage] to
    /// [HomePage].
    await HoshiDicts.preloadTransforms();

    final appModel = container.read(appProvider);
    await appModel.initialise();

    // ── 预热 WebView 引擎 ──────────────────────────────────────────────
    // 用户还在看主页/书架时就把冷启动成本吃掉：~500-1500ms。
    // Desktop: HeadlessInAppWebView may crash WebView2 if called before the
    // Flutter view is attached, so only warm up on mobile.
    if ((Platform.isAndroid || Platform.isIOS) && !appModel.lowMemoryMode) {
      unawaited(Future(() async {
        try {
          late final HeadlessInAppWebView warmup;
          warmup = HeadlessInAppWebView(
            initialUrlRequest: URLRequest(url: WebUri('about:blank')),
            onLoadStop: (controller, url) async {
              await Future.delayed(const Duration(milliseconds: 100));
              await warmup.dispose();
              debugPrint('[Hibiki] WebView engine pre-warmed');
            },
          );
          await warmup.run();
        } catch (e) {
          debugPrint('[Hibiki] WebView warmup failed (non-fatal): $e');
        }
      }));
    }

    /// Capture Flutter framework errors with full details.
    FlutterError.onError = (details) {
      // Suppress known Flutter framework bug: RawTooltipState creates
      // multiple tickers from SingleTickerProviderStateMixin.
      final msg = details.exceptionAsString();
      if (msg.contains('SingleTickerProviderStateMixin') &&
          msg.contains('RawTooltipState')) {
        return;
      }
      FlutterError.presentError(details);
      ErrorLogService.instance.log(
        'FlutterError: ${details.context?.toString() ?? 'unknown'}',
        msg,
        details.stack,
      );
    };
  }, (exception, stack) {
    /// Print error details to the console.
    final details = FlutterErrorDetails(exception: exception, stack: stack);

    /// Log the error.
    ErrorLogService.instance.log('UncaughtZone', exception, stack);
    if (Platform.isAndroid || Platform.isIOS) {
      FlutterLogs.logError(
        'hoshi_reader',
        details.exceptionAsString(),
        stack.toString(),
      );
    }
  });
}

/// Encapsulates theming, spacing and other configurable options pertaining to
/// the entire app, with some parameters dependent on the [AppModel].
class HoshiReaderApp extends ConsumerStatefulWidget {
  /// Initialises an instance of the app.
  const HoshiReaderApp({super.key});

  @override
  ConsumerState<HoshiReaderApp> createState() => _HoshiReaderAppState();
}

class _HoshiReaderAppState extends ConsumerState<HoshiReaderApp>
    with WidgetsBindingObserver {
  final navigatorKey = GlobalKey<NavigatorState>();
  bool _isMainIntent = true;
  StreamSubscription? _intentsSubscription;

  @override
  void initState() {
    super.initState();

    WidgetsBinding.instance.addObserver(this);
    HibikiToast.navigatorKey = ref.read(appProvider).navigatorKey;

    if (Platform.isAndroid) {
      WidgetsBinding.instance.addPostFrameCallback((_) async {
        intents.ReceiveIntent.getInitialIntent().then(
          (intent) => handleIntent(
            intent: intent,
            isInitial: true,
          ),
        );
        _intentsSubscription =
            intents.ReceiveIntent.receivedIntentStream.listen(
          (intent) => handleIntent(
            intent: intent,
            isInitial: false,
          ),
        );
      });
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      ref.read(appProvider).refreshSystemPalette();
    }
  }

  @override
  void dispose() {
    _intentsSubscription?.cancel();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  void handleIntent({
    required intents.Intent? intent,
    required bool isInitial,
  }) async {
    if (intent == null || !mounted) {
      return;
    }

    final String? data = intent.data;
    if (data != null && data.startsWith('hibiki://auth/')) {
      await _handleOAuthRedirect(data);
      return;
    }

    switch (intent.action) {
      case 'android.intent.action.MAIN':
        setState(() {
          _isMainIntent = true;
        });
        return;
    }
  }

  /// Completes a cloud-sync OAuth flow when the browser redirects back via
  /// `hibiki://auth/<provider>?code=...`. The pending PKCE verifier/repo were
  /// stored by the backend's `authenticate()` call before the browser opened.
  Future<void> _handleOAuthRedirect(String data) async {
    final Uri? uri = Uri.tryParse(data);
    if (uri == null || uri.host != 'auth' || uri.pathSegments.isEmpty) return;

    final String provider = uri.pathSegments.first;
    final String? code = uri.queryParameters['code'];
    final String? error = uri.queryParameters['error'];
    if (code == null) {
      HibikiToast.show(
          msg: t.sync_auth_error(message: error ?? 'missing code'));
      return;
    }

    try {
      switch (provider) {
        case 'onedrive':
          await OneDriveSyncBackend.instance.handleAuthCode(code);
        case 'dropbox':
          await DropboxSyncBackend.instance.handleAuthCode(code);
        default:
          return;
      }
      HibikiToast.show(msg: t.sync_signed_in);
    } on SyncAuthError catch (e) {
      HibikiToast.show(
          msg: t.sync_auth_error(message: friendlySyncErrorDetail(e)));
    } catch (e) {
      HibikiToast.show(msg: friendlySyncError(e));
    }
  }

  @override
  Widget build(BuildContext context) {
    // Fields like locales/targetLanguage/theme are late and only available
    // after initialise() completes. Return a minimal app while loading.
    // LoadingPage calls Spacing.of(context) via buildLoading(), so we must
    // not use it here — render the spinner directly instead.
    //
    // Use system brightness to match the native splash and avoid a white
    // flash when the user has dark mode enabled.
    if (appModel.initError != null) {
      final brightness =
          WidgetsBinding.instance.platformDispatcher.platformBrightness;
      final cs = ColorScheme.fromSeed(
        seedColor: const Color(0xFF1F4959),
        brightness: brightness,
      );
      return TranslationProvider(
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: ThemeData(useMaterial3: true, colorScheme: cs),
          home: Scaffold(
            backgroundColor: _savedSplashColor,
            body: Center(
              child: Padding(
                padding: const EdgeInsets.all(24),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.error_outline, size: 48, color: cs.error),
                    const SizedBox(height: 16),
                    Text(
                      t.initialization_failed,
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.bold,
                        color: cs.onSurface,
                      ),
                    ),
                    const SizedBox(height: 12),
                    SelectableText(
                      appModel.initError!,
                      style: TextStyle(
                        fontSize: 12,
                        color: cs.onSurfaceVariant,
                      ),
                      textAlign: TextAlign.center,
                      selectionControls: HibikiTextSelectionControls(
                        shareAction: (text) => Share.share(text),
                        allowCopy: true,
                        allowCut: false,
                        allowPaste: false,
                        allowSelectAll: true,
                      ),
                    ),
                    const SizedBox(height: 20),
                    Wrap(
                      spacing: 12,
                      runSpacing: 8,
                      alignment: WrapAlignment.center,
                      children: [
                        FilledButton.icon(
                          icon: const Icon(Icons.refresh, size: 18),
                          label: Text(t.retry),
                          onPressed: () => appModel.retryInitialise(),
                        ),
                        OutlinedButton.icon(
                          icon: const Icon(Icons.copy, size: 18),
                          label: Text(t.copy_error),
                          onPressed: () {
                            Clipboard.setData(
                              ClipboardData(text: appModel.initError!),
                            );
                            HibikiToast.show(msg: t.error_copied);
                          },
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    }
    if (!appModel.isInitialised) {
      final brightness =
          WidgetsBinding.instance.platformDispatcher.platformBrightness;
      final cs = ColorScheme.fromSeed(
        seedColor: const Color(0xFF1F4959),
        brightness: brightness,
      );
      return TranslationProvider(
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          theme: ThemeData(useMaterial3: true, colorScheme: cs),
          home: Scaffold(
            backgroundColor: _savedSplashColor,
            body: Center(
              child: CircularProgressIndicator(color: cs.primary),
            ),
          ),
        ),
      );
    }

    return TranslationProvider(
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        navigatorKey: appModel.navigatorKey,
        home: home,
        locale: locale,
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
        ],
        supportedLocales: appModel.locales.values,
        themeMode: themeMode,
        theme: appModel.theme,
        darkTheme: appModel.darkTheme,
        // This is responsible for the initialising the global spacing across
        // the entire project, making use of the [spaces] package.
        builder: (context, child) {
          final cs = Theme.of(context).colorScheme;
          return CupertinoTheme(
            data: hibikiCupertinoTheme(cs),
            child: Spacing(
              dataBuilder: (context) {
                return SpacingData.generate(10);
              },
              // Keyboard/gamepad navigation: a visible focus ring for
              // observability (keyboard + gamepad), wrapping the global
              // gamepad-B back/dismiss intent. The B-button mapping is
              // mobile-only — desktop never emits gameButton* keys — so it is
              // gated on the same predicate as the rest of the gamepad layer.
              child: HibikiFocusRing(
                child: wrapWithGlobalNavigation(
                  navigatorKey: appModel.navigatorKey,
                  enableGamepad:
                      ShortcutDefaults.gamepadSupported(defaultTargetPlatform),
                  child: child!,
                ),
              ),
            ),
          );
        },
      ),
    );
  }

  /// Responsible for managing global app-wide state.
  AppModel get appModel => ref.watch(appProvider);

  /// The application will open to this page upon startup.
  Widget get home => _isMainIntent ? const HomePage() : const Scaffold();

  ThemeMode get themeMode => appModel.themeMode;

  /// The current locale, dependent on the active target language.
  Locale get locale => appModel.targetLanguage.locale;
}
